package Component;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import kelompokan.koneksi;
public class DataWargaNew extends javax.swing.JPanel {
    public DataWargaNew() {
        initComponents();
        tampilData();  
        ButtonGroup groupKelamin = new ButtonGroup();
        groupKelamin.add(tLaki);
        groupKelamin.add(tPerempuan);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tNik = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAlamat = new javax.swing.JTextArea();
        tl = new javax.swing.JTextField();
        noHp = new javax.swing.JTextField();
        tAgama = new javax.swing.JComboBox<>();
        tStatus = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        tKWG = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        tPerempuan = new javax.swing.JRadioButton();
        tLaki = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        pendidikan = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtKerjaan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tMasuk = new de.wannawork.jcalendar.JCalendarComboBox();
        jCalendarComboBox1 = new de.wannawork.jcalendar.JCalendarComboBox();
        jPanel3 = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        tCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tWarga = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(757, 645));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(768, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Warga.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Form Data Warga");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/LogOut.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 948, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1130, 50);

        jPanel2.setBackground(new java.awt.Color(94, 89, 128));
        jPanel2.setPreferredSize(new java.awt.Dimension(757, 100));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIK");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Lengkap");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tempat/Tgl lahir");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Agama");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Status");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("No Telepon");

        tAlamat.setColumns(20);
        tAlamat.setRows(5);
        jScrollPane2.setViewportView(tAlamat);

        tAgama.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Islam", "Kristen Protestan", "Kristen Katolik", "Hindu", "Buddha", "Konghucu", " " }));

        tStatus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Belum Kawin", "Kawin", "Cerai Hidup", "Cerai Mati" }));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Kewarganegaraan");

        tKWG.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tKWG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Indonesia", "Malaisya", "Vietnam", "Thailand", "Cambodia", "Myanmar" }));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Jenis Kelamin");

        buttonGroup1.add(tPerempuan);
        tPerempuan.setForeground(new java.awt.Color(255, 255, 255));
        tPerempuan.setText("Perempuan");

        buttonGroup1.add(tLaki);
        tLaki.setForeground(new java.awt.Color(255, 255, 255));
        tLaki.setText("Laki-laki");
        tLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tLakiActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Pendidikan Terakhir");

        pendidikan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pendidikan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "SD/MI", "SMP/MTS", "SMA/SMK", "D3", "S1", "S2", "S3" }));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Pekerjaan");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tanggal Masuk");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tNama)
                    .addComponent(tNik)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tPerempuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tl, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tLaki, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jCalendarComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(noHp)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKerjaan)
                            .addComponent(pendidikan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tAgama, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(tKWG, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPerempuan)
                    .addComponent(tLaki)
                    .addComponent(jLabel11))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(tl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCalendarComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tKWG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtKerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(tMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel2);
        jPanel2.setBounds(0, 50, 1130, 410);

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        btnClear.setBackground(new java.awt.Color(38, 50, 56));
        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(38, 50, 56));
        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setPreferredSize(new java.awt.Dimension(63, 23));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(38, 50, 56));
        btnEdit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.setPreferredSize(new java.awt.Dimension(63, 23));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(38, 50, 56));
        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setPreferredSize(new java.awt.Dimension(63, 23));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCari.setBackground(new java.awt.Color(38, 50, 56));
        btnCari.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setText("Cari");
        btnCari.setPreferredSize(new java.awt.Dimension(63, 23));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnClear)
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 480, Short.MAX_VALUE)
                .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(jPanel3);
        jPanel3.setBounds(0, 460, 1130, 50);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 600));

        tWarga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tWarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tWargaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tWarga);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 510, 1130, 170);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String jk ="";
        if(tLaki.isSelected()){
         jk = "Laki-laki";
        }else if(tPerempuan.isSelected()){
         jk = "Perempuan";
        }else{
         JOptionPane.showMessageDialog(null,"pilih jenis kelamin terlebih dahulu!");
         return;
        }
        try (Connection conn = new koneksi().connect()) {
            String sql = "INSERT INTO datawarga (nik, nama, jk, tl, tg, noTlp, alamat, kwg, pendidikan, pekerjaan, agama, statusW, tglMasuk) "
                       + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, tNik.getText());
            pst.setString(2, tNama.getText());
            pst.setString(3, jk);
            pst.setString(4, tl.getText());
            pst.setDate(5, new java.sql.Date(tMasuk.getDate().getTime()));
            pst.setString(6, noHp.getText());
            pst.setString(7, tAlamat.getText());
            pst.setString(8, tKWG.getSelectedItem().toString());
            pst.setString(9, pendidikan.getSelectedItem().toString());
            pst.setString(10, txtKerjaan.getText());
            pst.setString(11, tAgama.getSelectedItem().toString());
            pst.setString(12, tStatus.getSelectedItem().toString());
            pst.setDate(13, new java.sql.Date(tMasuk.getDate().getTime()));
            
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
            tampilData();
            resetForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
         String jk = "";
    if (tLaki.isSelected()) {
        jk = "Laki-laki";
    } else if (tPerempuan.isSelected()) {
        jk = "Perempuan";
    } else {
        JOptionPane.showMessageDialog(null, "Pilih jenis kelamin!");
        return;
    }

    try (Connection conn = new koneksi().connect()) {

        String sql = "UPDATE datawarga SET nama=?, jk=?, tl=?, tg=?, noTlp=?, alamat=?, kwg=?, pendidikan=?, pekerjaan=?, agama=?, statusW=?, tglMasuk=? WHERE nik=?";

        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, tNama.getText());
        pst.setString(2, jk);
        pst.setString(3, tl.getText());
        pst.setDate(4, new java.sql.Date(tMasuk.getDate().getTime()));
        pst.setString(5, noHp.getText());
        pst.setString(6, tAlamat.getText());
        pst.setString(7, tKWG.getSelectedItem().toString());
        pst.setString(8, pendidikan.getSelectedItem().toString());
        pst.setString(9, txtKerjaan.getText());
        pst.setString(10, tAgama.getSelectedItem().toString());
        pst.setString(11, tStatus.getSelectedItem().toString());
        pst.setDate(12, new java.sql.Date(tMasuk.getDate().getTime()));
        pst.setString(13, tNik.getText()); // WHERE

        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil diubah");

        tampilData();
        resetForm();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal edit: " + e.getMessage());
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(
        this,
        "Yakin ingin menghapus data ini?",
        "Konfirmasi",
        JOptionPane.YES_NO_OPTION
    );

    if (konfirmasi != JOptionPane.YES_OPTION) return;

    try (Connection conn = new koneksi().connect()) {

        String sql = "DELETE FROM datawarga WHERE nik=?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, tNik.getText());
        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil dihapus");

        tampilData();   // 🔥 REFRESH TABLE
        resetForm();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal hapus: " + e.getMessage());
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIK");
        model.addColumn("Nama Lengkap");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Tempat Lahir");
        model.addColumn("Tgl Lahir");
        model.addColumn("No Telepon");
        model.addColumn("Alamat");
        model.addColumn("Kewarganegaraan");
        model.addColumn("Pendidikan Terakhir");
        model.addColumn("Pekerjaan");
        model.addColumn("Agama");
        model.addColumn("Status");
        model.addColumn("Tanggal Masuk");

        try {
            String keyword = tCari.getText();
            String sql = "SELECT * FROM datawarga WHERE nik LIKE ? OR nama LIKE ?";
            java.sql.Connection conn = new kelompokan.koneksi().connect();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + keyword + "%");
            pst.setString(2, "%" + keyword + "%");

            java.sql.ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("nik"),
                    rs.getString("nama"),
                    rs.getString("jk"),
                    rs.getString("tl"),
                    rs.getString("tg"),
                    rs.getString("noTlp"),
                    rs.getString("alamat"),
                    rs.getString("kwg"),
                    rs.getString("pendidikan"),
                    rs.getString("pekerjaan"),
                    rs.getString("agama"),
                    rs.getString("statusW"),
                    rs.getString("tglMasuk")
                });
            }
            tWarga.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Pencarian gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void tLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tLakiActionPerformed

    private void tWargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tWargaMouseClicked
        int baris = tWarga.rowAtPoint(evt.getPoint());
    if (baris >= 0) {
      
        String nik = tWarga.getModel().getValueAt(baris, 0).toString();
        tNik.setText(nik);
        String nama = tWarga.getModel().getValueAt(baris, 1).toString();
        tNama.setText(nama);
        String jenisKelamin = tWarga.getModel().getValueAt(baris, 2).toString();
        if (jenisKelamin.equals("Laki-laki")) {
            tLaki.setSelected(true);
            tPerempuan.setSelected(false);
        } else if (jenisKelamin.equals("Perempuan")) {
            tPerempuan.setSelected(true);
            tLaki.setSelected(false);
        } else {
             tLaki.setSelected(false);
             tPerempuan.setSelected(false);
        }
        
        // Kolom 3: Tempat Lahir
        String tempatLahir = tWarga.getModel().getValueAt(baris, 3).toString();
        tl.setText(tempatLahir);
        try {
            String tglLahirStr = tWarga.getModel().getValueAt(baris, 4).toString();
            java.util.Date tglLahir = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tglLahirStr);
           
        } catch (java.text.ParseException | NullPointerException ex) {
            // Abaikan atau tampilkan pesan error jika gagal parsing tanggal
        }

        String noTlp = tWarga.getModel().getValueAt(baris, 5).toString();
        noHp.setText(noTlp);

        String alamat = tWarga.getModel().getValueAt(baris, 6).toString();
        tAlamat.setText(alamat);

        String kwg = tWarga.getModel().getValueAt(baris, 7).toString();
        tKWG.setSelectedItem(kwg);
 
        String pendidikanTerakhir = tWarga.getModel().getValueAt(baris, 8).toString();
        pendidikan.setSelectedItem(pendidikanTerakhir);

        String pekerjaan = tWarga.getModel().getValueAt(baris, 9).toString();
        txtKerjaan.setText(pekerjaan);

        String agama = tWarga.getModel().getValueAt(baris, 10).toString();
        tAgama.setSelectedItem(agama);

        String status = tWarga.getModel().getValueAt(baris, 11).toString();
        tStatus.setSelectedItem(status);

        try {
            String tglMasukStr = tWarga.getModel().getValueAt(baris, 12).toString();
            java.util.Date tglMasukDate = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tglMasukStr);
            // Asumsi field input Tanggal Masuk adalah tMasuk
            tMasuk.setDate(tglMasukDate); 
        } catch (java.text.ParseException | NullPointerException ex) {
            // Abaikan atau tampilkan pesan error
        }
    }
    }//GEN-LAST:event_tWargaMouseClicked

    private void resetForm() {
    // Mengosongkan JTextfield
    tNik.setText("");
    tNama.setText("");
    tl.setText("");
    noHp.setText("");
    tAlamat.setText("");
    txtKerjaan.setText("");
    tCari.setText(""); 

    // Mengatur ulang JComboBox ke indeks pertama
    tAgama.setSelectedIndex(0);
    tStatus.setSelectedIndex(0);
    tKWG.setSelectedIndex(0);
    pendidikan.setSelectedIndex(0);


    buttonGroup1.clearSelection(); 

    // Mengosongkan JDateChooser (asumsi tMasuk adalah JDateChooser Anda)
    tMasuk.setDate(null);

    }
    
    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIK");
        model.addColumn("Nama Lengkap");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Tempat Lahir");
        model.addColumn("Tgl Lahir");
        model.addColumn("No Telepon");
        model.addColumn("Alamat");
        model.addColumn("Kewarganegaraan");
        model.addColumn("Pendidikan Terakhir");
        model.addColumn("Pekerjaan");
        model.addColumn("Agama");
        model.addColumn("Status");
        model.addColumn("Tanggal Masuk");
        try (Connection conn = new koneksi().connect()) {
            String sql = "SELECT * FROM datawarga ORDER BY NIK DESC";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[] {
                    rs.getString("nik"),
                    rs.getString("nama"),
                    rs.getString("jk"),
                    rs.getString("tl"),
                    rs.getString("tg"),
                    rs.getString("noTlp"),
                    rs.getString("alamat"),
                    rs.getString("kwg"),
                    rs.getString("pendidikan"),
                    rs.getString("pekerjaan"),
                    rs.getString("agama"),
                    rs.getString("statusW"),
                    rs.getString("tglMasuk")
                });
            }
            tWarga.setModel(model); // tableWarga adalah nama JTable
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal menampilkan data: " + e.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private de.wannawork.jcalendar.JCalendarComboBox jCalendarComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField noHp;
    private javax.swing.JComboBox<String> pendidikan;
    private javax.swing.JComboBox<String> tAgama;
    private javax.swing.JTextArea tAlamat;
    private javax.swing.JTextField tCari;
    private javax.swing.JComboBox<String> tKWG;
    private javax.swing.JRadioButton tLaki;
    private de.wannawork.jcalendar.JCalendarComboBox tMasuk;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tNik;
    private javax.swing.JRadioButton tPerempuan;
    private javax.swing.JComboBox<String> tStatus;
    private javax.swing.JTable tWarga;
    private javax.swing.JTextField tl;
    private javax.swing.JTextField txtKerjaan;
    // End of variables declaration//GEN-END:variables
}
